# Section 1: Downloading numpy

In collab all you need it :

#### import numpy

In terminal, or other mediums, you need to download it with :

####  pip install numpy

The convention is to rename it as np, that way each time you call it, you dont't need to write out numpy, you can just abbreviate with np

In [ ]:
import numpy as np

# Section 2: The NP Array

Call it by np.array(), you can cast with this just like we have been with lists and sets before.

np.arrays are special in that they can be ore than 1 dimention.

They have their own sets of calls

In [ ]:
#Standard Array

# arr = np.array([1, 2, 3, 4, 5])

# print(arr)


#DATA TYPES

# arr = np.array(['apple', 'banana', 'cherry'])

# print(arr.dtype)

#https://numpy.org/doc/1.18/reference/generated/numpy.dtype.html

#2

# arr = np.array([1, 2, 3, 4], dtype='S')

# print(arr)
# print(arr.dtype)



#INDEXING

# arr = np.array([1, 2, 3, 4])

# print(arr[1])

# arr[0] = 0

# print(arr)


#SLICING

# arr = np.array([1, 2, 3, 4, 5, 6, 7])

# print(arr[1:5])


#FILLING

# arr = np.arange(2,5)

# print(arr)


#DIMENSIONS

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(len(c))

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)




#INDEXING 2D Array

# arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

# print('2nd element on 1st dim: ', arr[0, 1])


#RESHAPING

# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# newarr = arr.reshape(4, 4)

# print(newarr)

2
0
1
2
3


In [ ]:
#INSERTING

# arr = np.array([1,2,3,4])
# arr = np.insert(arr, 2, 66)

# print(arr)


#ITERATING

# arr = np.array([1, 2, 3]) #SAME AS LIST!!

# for x in arr:
#   print(x)


# arr = np.array([[1, 2, 3], [4, 5, 6]])

# for x in arr:
#   print(x)


# arr = np.array([[1, 2, 3], [4, 5, 6]])

# for x in arr:
#   for y in x:
#     print(y)



#JOING ARRAYS

# arr1 = np.array([1, 2, 3])

# arr2 = np.array([4, 5, 6])

# arr = np.concatenate((arr1, arr2))

# print(arr)


#SEARCH

# arr = np.array([1, 2, 3, 4, 5, 4, 4])

# x = np.where(arr == 4)

# print(x)


#NP ZEROS

arr1 = np.zeros(5)

arr = np.insert(arr1, 1, 7)

# arr2 = np.zeros((3, 2))

print(arr)
# print(arr2)

[0. 7. 0. 0. 0. 0.]


# Section 3: Matrix

Since this is a linear algebra course, we'll be dealing a lot with 1-dimensional vectors and 2-dimensional matrices. The obvious way to represent these in code are 1-dim and 2-dim arrays.

Let's look at representing the following vectors and matrices:

$\mathbf{u} = \begin{bmatrix} 1 & 0 & 4 & 6 \end{bmatrix}$

$\mathbf{v} =  \begin{bmatrix} 1 \\ 0 \\ 4 \\ 6 \end{bmatrix}$

$\mathbf{A} = \begin{bmatrix} 4 & 6 & 2 & 0 \\ 3 & 7 & 2 & 9 \\ 0 & 1 & 4 & 2 \\ 9 & 3 & 5 & 6 \end{bmatrix} $

In [ ]:
u = [[1, 0, 4, 6]]
v = [[1],
     [0],
     [4],
     [6]]
A = [[4, 6, 2, 0], 
     [3, 7, 2, 9],
     [0, 1, 4, 2],
     [9, 3, 5, 6]]

### You do not need to nderstand the math here, but just to see what cool stuff numpy can do!

Consider the following chemical equation, where iron(II) sulfide combusts with oxygen to form iron(III) oxide and sulfur dioxide gas:

FeS + O$_2$ $\rightarrow$ Fe$_2$O$_3$ + SO$_2$

However, this equation needs to be balanced, as the number of each atom does not match between the left side and right side. For example, the left side has two oxygen atoms, while the right side has five.

In [ ]:

# Define your matrix representation here as a numpy array:

A = np.array([[0, 0, 1, 0],
              [1, 0, -2, 0],
              [1, 0, 0, -1],
              [0, 2, -3, -2]])

b = np.array([1, 0, 0, 0])



In [ ]:
# BALANCE! 

def balance(A, b):
    coeffs = np.linalg.solve(A,b)*2
    return coeffs

print(balance(A, b))


[4. 7. 2. 4.]


Which produces:

$4$FeS + $7$O$_2$ $\rightarrow$ $2$Fe$_2$O$_3$ + $4$SO$_2$

## Further Applications

Example of "from" import

Again don't worry about the math

In [ ]:
from math import exp


print(exp(3))



20.085536923187668


NameError: ignored

For more help

Complete Numpy documentation:

https://docs.scipy.org/doc/numpy/

Stanford CS231n Python/Numpy Tutorial:

http://cs231n.github.io/python-numpy-tutorial/

## LABS

1. Write a NumPy program to create an array of all the even integers from 30 to 70.

2. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

3. Write a NumPy program to create a 3x3 matrix/array with values ranging from 2 to 10.

4. Write a NumPy program to create a 0 array of size 10 and update sixth value to 11



## Solutions:

In [ ]:
#1
array = np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(array) 


Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
#2
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
#3
x =  np.arange(2, 11).reshape(3,3)
print(x)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
#4
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [ ]:
import numpy as np

In [ ]:
goal = [0,1,2,3,4,5,6,7,8]
actual = [7,2,4,5,0,6,8,3,1]

g2 = np.array(goal).reshape(3,3)
a2 = np.array(actual).reshape(3,3)
tots = 0 

for i in range(1, len(goal)):
  x,y = (np.where(a2 == i))
  x_goal, y_goal = (np.where(g2 == i))
  tots += (abs(x[0]-x_goal[0])+ abs(y[0]-y_goal[0]))
  print(tots)



3
4
6
8
10
13
16
18


In [ ]:
front = [(0,[7,2,4,5,0,6,8,3,1]), (5,[5,6]), (2,[2,3,5,7,3,5]), (1,[100]) ]
print(front)

print(front[1])

[(0, [7, 2, 4, 5, 0, 6, 8, 3, 1]), (5, [5, 6]), (2, [2, 3, 5, 7, 3, 5]), (1, [100])]
(5, [5, 6])


In [ ]:
def Sort_Tuple(tup):  
  
    # reverse = None (Sorts in Ascending order)  
    # key is set to sort using second element of  
    # sublist lambda has been used  
    tup.sort(key = lambda x: x[0])  
    return tup  
  
# Driver Code  
tup = [('rishav', 10), ('akash', 5), ('ram', 20), ('gaurav', 15)]  
  
# printing the sorted list of tuples 
print(Sort_Tuple(front))  

[(0, [7, 2, 4, 5, 0, 6, 8, 3, 1]), (1, [100]), (2, [2, 3, 5, 7, 3, 5]), (5, [5, 6])]


In [ ]:
goal = [0,1,2,3,4,5,6,7,8]
actual = [7,2,4,5,0,6,8,3,1]
temp = [7,2,4,5,0,4,8,3,1]

import queue as Q
import copy



test = set()
test.add(tuple(goal))
test.add(tuple(actual))

if tuple(temp) not in test:
  print("nope")
  







# front = Q.Queue()
# front.put(actual)
# front.put(goal)

# test = Q.Queue()

# while not front.empty():
#   elem = front.get()
#   if elem == temp:
#     print("here")
#     test.put(elem)
#     break
#   else:
#     test.put(elem)
#     print("nope")

# #print(test.get())
# front = Q.Queue()
# front = test
# print(front.get())

nope
